04:53:08 PM:DEBUG [logger_base.py:13] Mensaje a nivel debug
04:53:08 PM:INFO [logger_base.py:14] Mensaje a nivel info
04:53:08 PM:WARNING [logger_base.py:15] Mensaje a nivel warning
04:53:08 PM:ERROR [logger_base.py:16] Mensaje a nivel error
04:53:08 PM:CRITICAL [logger_base.py:17] Mensaje a nivel critical

05:20:39 PM:DEBUG [Persona.py:53] 
            Id Persona: 1,
            Nombre: Juan,
            Apellido: Perez
            Email: jperez@mail.com
        
05:23:20 PM:DEBUG [Persona.py:54] 
            Id Persona: 1,
            Nombre: Juan,
            Apellido: Perez
            Email: jperez@mail.com
        
05:23:20 PM:DEBUG [Persona.py:56] 
            Id Persona: Jose,
            Nombre: Lepez,
            Apellido: ljose@mail.com
            Email: None
        
05:23:44 PM:DEBUG [Persona.py:54] 
            Id Persona: 1,
            Nombre: Juan,
            Apellido: Perez
            Email: jperez@mail.com
        
05:23:44 PM:DEBUG [Persona.py:56] 
            Id Persona: None,
            Nombre: Jose,
            Apellido: Lepez
            Email: ljose@mail.com
        
05:25:18 PM:DEBUG [Persona.py:54] 
            Id Persona: 1,
            Nombre: Juan,
            Apellido: Perez
            Email: jperez@mail.com
        
05:25:18 PM:DEBUG [Persona.py:56] 
            Id Persona: None,
            Nombre: Jose,
            Apellido: Lepez
            Email: ljose@mail.com
        
05:25:18 PM:DEBUG [Persona.py:58] 
            Id Persona: 1,
            Nombre: None,
            Apellido: None
            Email: None
        
06:03:49 PM:DEBUG [conexion.py:24] Conexion Exitosa: <connection object at 0x0000022974864BF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
06:03:49 PM:DEBUG [conexion.py:37] Se abrio correctamente el cursor: <cursor object at 0x000002297450B5A0; closed: 0>
